services:
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - ./logs:/app/logs
        links:
            - db

    db:
        image: "postgres:17.6"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - ./db-data:/var/lib/postgresql/data/

    # database administration
    adminer:
        image: adminer
        environment:
            ADMINER_DEFAULT_SERVER: postgres_server
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - db
