services:
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        links:
            - db

    db:
        image: "postgres:15.10"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    # database administration
    adminer:
        image: adminer
        environment:
            ADMINER_DEFAULT_SERVER: postgres_server
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - db
